# Generated by Django 3.0.7 on 2021-01-12 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0007_auto_20210112_0648'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeCarton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('created_at', models.DateTimeField(default='2020-06-29', editable=False)),
                ('carton', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.Impresion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
