# Generated by Django 3.0.7 on 2021-01-13 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_auto_20210112_0648'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeCarton75',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('created_at', models.DateTimeField(default='2020-06-29', editable=False)),
                ('carton', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.Impresion75')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
