from django.db import migrations, models
import django.db.models.deletion
from decimal import Decimal

class Migration(migrations.Migration):
    dependencies=[('pagos','0004_payment_currency'),('partidas','0006_financial_decimal')]
    operations=[
        migrations.CreateModel(name='Settlement',fields=[('id',models.AutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('status',models.CharField(choices=[('LIQUIDADA','Liquidada')],default='LIQUIDADA',max_length=12)),('sold_cards',models.PositiveIntegerField(default=0)),('pool',models.DecimalField(decimal_places=2,default=Decimal('0.00'),max_digits=14)),('prize_gross',models.DecimalField(decimal_places=2,default=Decimal('0.00'),max_digits=14)),('tax',models.DecimalField(decimal_places=2,default=Decimal('0.00'),max_digits=14)),('prize_net',models.DecimalField(decimal_places=2,default=Decimal('0.00'),max_digits=14)),('settled_at',models.DateTimeField(auto_now_add=True)),('partida',models.OneToOneField(on_delete=django.db.models.deletion.PROTECT,related_name='settlement',to='partidas.Partida')),('settled_by',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='settlements',to='auth.User'))]),
        migrations.CreateModel(name='Settlement75',fields=[('id',models.AutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('status',models.CharField(choices=[('LIQUIDADA','Liquidada')],default='LIQUIDADA',max_length=12)),('sold_cards',models.PositiveIntegerField(default=0)),('pool',models.DecimalField(decimal_places=2,default=Decimal('0.00'),max_digits=14)),('prize_gross',models.DecimalField(decimal_places=2,default=Decimal('0.00'),max_digits=14)),('tax',models.DecimalField(decimal_places=2,default=Decimal('0.00'),max_digits=14)),('prize_net',models.DecimalField(decimal_places=2,default=Decimal('0.00'),max_digits=14)),('settled_at',models.DateTimeField(auto_now_add=True)),('partida',models.OneToOneField(on_delete=django.db.models.deletion.PROTECT,related_name='settlement75',to='partidas.Partida75')),('settled_by',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='settlements75',to='auth.User'))]),
    ]
