# Generated by Django 3.0.7 on 2020-09-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moneda', models.CharField(max_length=255)),
                ('corresponsal', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=255)),
                ('codigo_swift', models.CharField(blank=True, max_length=255)),
                ('banco_benef', models.CharField(max_length=255)),
                ('cuenta', models.CharField(max_length=255)),
                ('beneficiario_final', models.CharField(max_length=255)),
                ('cuenta_abono', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(editable=False)),
            ],
        ),
    ]
