# Generated by Django 3.0.7 on 2020-12-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fondo_login_desktop', models.ImageField(default='fondos/fondo_portada.jpg', upload_to='fondos/')),
                ('fondo_login_mobile', models.ImageField(default='fondos/fondo_portada.jpg', upload_to='fondos/')),
            ],
        ),
    ]
