# Generated by Django 3.0.7 on 2020-12-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='fondo_pantalla_bingo',
            field=models.ImageField(default='fondos/fondo_portada.jpg', upload_to='fondos/'),
        ),
        migrations.AddField(
            model_name='config',
            name='fondo_pantalla_mexicana',
            field=models.ImageField(default='fondos/fondo_portada.jpg', upload_to='fondos/'),
        ),
    ]
