# Generated by Django 3.0.7 on 2020-12-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_auto_20201208_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='fondo_carton_bingo',
            field=models.ImageField(default='fondos/fondo_carton_bingo.png', upload_to='fondos/'),
        ),
        migrations.AddField(
            model_name='config',
            name='fondo_carton_lotoMX',
            field=models.ImageField(default='fondos/fondo_carton_lotoMX.png', upload_to='fondos/'),
        ),
        migrations.AddField(
            model_name='config',
            name='logo_horizontal',
            field=models.ImageField(default='fondos/logo_horizontal.png', upload_to='fondos/'),
        ),
    ]
