# Generated by Django 3.0.7 on 2020-12-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0003_auto_20201211_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='fondo_tablero_bingo_75',
            field=models.ImageField(default='fondos/fondo_tablero_bingo_75.png', upload_to='fondos/'),
        ),
        migrations.AddField(
            model_name='config',
            name='tapa_balota_bingo',
            field=models.ImageField(default='fondos/tapa_balota_bingo.png', upload_to='fondos/'),
        ),
        migrations.AddField(
            model_name='config',
            name='tapa_carta_lotoMX',
            field=models.ImageField(default='fondos/tapa_carta_lotoMX.png', upload_to='fondos/'),
        ),
        migrations.AlterField(
            model_name='config',
            name='fondo_pantalla_bingo',
            field=models.ImageField(default='fondos/fondo_pantalla_bingo.png', upload_to='fondos/'),
        ),
        migrations.AlterField(
            model_name='config',
            name='fondo_pantalla_mexicana',
            field=models.ImageField(default='fondos/fondo_pantalla_mexicana.jpg', upload_to='fondos/'),
        ),
    ]
