# Generated by Django 3.0.7 on 2020-12-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0004_auto_20201212_0556'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='logo',
            field=models.ImageField(default='fondos/logo.png', upload_to='fondos/'),
        ),
        migrations.AddField(
            model_name='config',
            name='titulo',
            field=models.CharField(default='SoftAndPlay', max_length=50),
        ),
    ]
