# Generated by Django 3.0.7 on 2021-01-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0005_auto_20201222_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='impuesto',
            field=models.CharField(default='12', max_length=50),
        ),
    ]
