# Generated by Django 3.0.7 on 2020-10-15 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partidas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partida75',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('partida', models.IntegerField(default=0)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('figura_1', models.BooleanField(default=False)),
                ('ganador_1', models.BooleanField(default=False)),
                ('monto_1', models.CharField(blank=True, default='0', max_length=50)),
                ('figura_2', models.BooleanField(default=False)),
                ('ganador_2', models.BooleanField(default=False)),
                ('monto_2', models.CharField(blank=True, default='0', max_length=50)),
                ('figura_3', models.BooleanField(default=False)),
                ('ganador_3', models.BooleanField(default=False)),
                ('monto_3', models.CharField(blank=True, default='0', max_length=50)),
                ('figura_4', models.BooleanField(default=False)),
                ('ganador_4', models.BooleanField(default=False)),
                ('monto_4', models.CharField(blank=True, default='0', max_length=50)),
                ('figura_5', models.BooleanField(default=False)),
                ('ganador_5', models.BooleanField(default=False)),
                ('monto_5', models.CharField(blank=True, default='0', max_length=50)),
                ('figura_6', models.BooleanField(default=False)),
                ('ganador_6', models.BooleanField(default=False)),
                ('monto_6', models.CharField(blank=True, default='0', max_length=50)),
                ('figura_7', models.BooleanField(default=False)),
                ('ganador_7', models.BooleanField(default=False)),
                ('monto_7', models.CharField(blank=True, default='0', max_length=50)),
                ('figura_8', models.BooleanField(default=False)),
                ('ganador_8', models.BooleanField(default=False)),
                ('monto_8', models.CharField(blank=True, default='0', max_length=50)),
                ('figura_9', models.BooleanField(default=False)),
                ('ganador_9', models.BooleanField(default=False)),
                ('monto_9', models.CharField(blank=True, default='0', max_length=50)),
                ('figura_10', models.BooleanField(default=False)),
                ('ganador_10', models.BooleanField(default=False)),
                ('monto_10', models.CharField(blank=True, default='0', max_length=50)),
                ('monto_carton', models.CharField(default='0', max_length=50)),
                ('termino', models.BooleanField(default=False)),
                ('inicio', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(editable=False, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Jugada75',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balota', models.CharField(blank=True, max_length=2)),
                ('orden', models.CharField(blank=True, max_length=2)),
                ('created_at', models.DateTimeField(editable=False, null=True)),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partidas.Partida75')),
            ],
        ),
    ]
