# Generated by Django 3.0.7 on 2021-01-14 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidas', '0002_jugada75_partida75'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='porciento_1',
            field=models.CharField(blank=True, default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='partida',
            name='porciento_10',
            field=models.CharField(blank=True, default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='partida',
            name='porciento_2',
            field=models.CharField(blank=True, default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='partida',
            name='porciento_3',
            field=models.CharField(blank=True, default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='partida',
            name='porciento_4',
            field=models.CharField(blank=True, default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='partida',
            name='porciento_5',
            field=models.CharField(blank=True, default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='partida',
            name='porciento_6',
            field=models.CharField(blank=True, default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='partida',
            name='porciento_7',
            field=models.CharField(blank=True, default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='partida',
            name='porciento_8',
            field=models.CharField(blank=True, default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='partida',
            name='porciento_9',
            field=models.CharField(blank=True, default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='partida75',
            name='porciento_1',
            field=models.CharField(blank=True, default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='partida75',
            name='porciento_10',
            field=models.CharField(blank=True, default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='partida75',
            name='porciento_2',
            field=models.CharField(blank=True, default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='partida75',
            name='porciento_3',
            field=models.CharField(blank=True, default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='partida75',
            name='porciento_4',
            field=models.CharField(blank=True, default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='partida75',
            name='porciento_5',
            field=models.CharField(blank=True, default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='partida75',
            name='porciento_6',
            field=models.CharField(blank=True, default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='partida75',
            name='porciento_7',
            field=models.CharField(blank=True, default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='partida75',
            name='porciento_8',
            field=models.CharField(blank=True, default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='partida75',
            name='porciento_9',
            field=models.CharField(blank=True, default='0', max_length=50),
        ),
    ]
