# Generated by Django 3.0.7 on 2021-01-14 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidas', '0003_auto_20210114_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='cartones_vendidos',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='partida',
            name='impuesto',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='partida',
            name='monto_acumulado',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='partida',
            name='total',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='partida75',
            name='cartones_vendidos',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='partida75',
            name='impuesto',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='partida75',
            name='monto_acumulado',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='partida75',
            name='total',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
