# Generated by Django 3.0.7 on 2020-09-28 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(default='Usuario', max_length=8)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('failds', models.IntegerField(default=0)),
                ('block', models.CharField(default='no', max_length=2)),
                ('country', models.CharField(max_length=3)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=250)),
                ('registered', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('thumb', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/')),
                ('created_at', models.DateTimeField(editable=False, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
