# Generated by Django 3.0.7 on 2021-01-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20210106_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='validado',
            field=models.BooleanField(default=False),
        ),
    ]
