# Generated by Django 3.0.7 on 2020-10-15 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0001_initial'),
        ('partidas', '0002_jugada75_partida75'),
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carton75',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l1_1', models.CharField(blank=True, max_length=2)),
                ('l1_2', models.CharField(blank=True, max_length=2)),
                ('l1_3', models.CharField(blank=True, max_length=2)),
                ('l1_4', models.CharField(blank=True, max_length=2)),
                ('l1_5', models.CharField(blank=True, max_length=2)),
                ('l2_1', models.CharField(blank=True, max_length=2)),
                ('l2_2', models.CharField(blank=True, max_length=2)),
                ('l2_3', models.CharField(blank=True, max_length=2)),
                ('l2_4', models.CharField(blank=True, max_length=2)),
                ('l2_5', models.CharField(blank=True, max_length=2)),
                ('l3_1', models.CharField(blank=True, max_length=2)),
                ('l3_2', models.CharField(blank=True, max_length=2)),
                ('l3_3', models.CharField(blank=True, max_length=2)),
                ('l3_4', models.CharField(blank=True, max_length=2)),
                ('l3_5', models.CharField(blank=True, max_length=2)),
                ('l4_1', models.CharField(blank=True, max_length=2)),
                ('l4_2', models.CharField(blank=True, max_length=2)),
                ('l4_3', models.CharField(blank=True, max_length=2)),
                ('l4_4', models.CharField(blank=True, max_length=2)),
                ('l4_5', models.CharField(blank=True, max_length=2)),
                ('l5_1', models.CharField(blank=True, max_length=2)),
                ('l5_2', models.CharField(blank=True, max_length=2)),
                ('l5_3', models.CharField(blank=True, max_length=2)),
                ('l5_4', models.CharField(blank=True, max_length=2)),
                ('l5_5', models.CharField(blank=True, max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Impresion75',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ganador_1', models.BooleanField(default=False)),
                ('posible_1', models.BooleanField(default=False)),
                ('ganador_2', models.BooleanField(default=False)),
                ('posible_2', models.BooleanField(default=False)),
                ('ganador_3', models.BooleanField(default=False)),
                ('posible_3', models.BooleanField(default=False)),
                ('ganador_4', models.BooleanField(default=False)),
                ('posible_4', models.BooleanField(default=False)),
                ('ganador_5', models.BooleanField(default=False)),
                ('posible_5', models.BooleanField(default=False)),
                ('ganador_6', models.BooleanField(default=False)),
                ('posible_6', models.BooleanField(default=False)),
                ('ganador_7', models.BooleanField(default=False)),
                ('posible_7', models.BooleanField(default=False)),
                ('ganador_8', models.BooleanField(default=False)),
                ('posible_8', models.BooleanField(default=False)),
                ('linea', models.IntegerField(default=0)),
                ('ganador_9', models.BooleanField(default=False)),
                ('posible_9', models.BooleanField(default=False)),
                ('ganador_10', models.BooleanField(default=False)),
                ('posible_10', models.BooleanField(default=False)),
                ('ganador', models.BooleanField(default=False)),
                ('ganador_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(editable=False, null=True)),
                ('enJuego', models.BooleanField(default=False)),
                ('pago', models.BooleanField(default=False)),
                ('carton', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.Carton')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.CabezeraImpre')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CabezeraImpre75',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cuenta', models.CharField(blank=True, max_length=30)),
                ('banco', models.CharField(blank=True, max_length=50)),
                ('referencia', models.CharField(blank=True, max_length=20)),
                ('cantidad', models.CharField(blank=True, max_length=2)),
                ('file', models.ImageField(upload_to='captures_bancos/')),
                ('verficado', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partidas.Partida75')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
