# Generated by Django 3.0.7 on 2020-10-17 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_cabezeraimpre75_carton75_impresion75'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impresion75',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.CabezeraImpre75'),
        ),
    ]
