# Generated by Django 3.0.7 on 2020-10-21 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_auto_20201017_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impresion75',
            name='carton',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.Carton75'),
        ),
    ]
