# Generated by Django 3.0.7 on 2021-01-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_auto_20201021_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='impresion',
            name='monto',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='impresion75',
            name='monto',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
