# Generated by Django 3.0.7 on 2021-01-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_auto_20210111_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='impresion',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='impresion75',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='impresion',
            name='monto',
            field=models.CharField(blank=True, default='0', max_length=30),
        ),
        migrations.AlterField(
            model_name='impresion75',
            name='monto',
            field=models.CharField(blank=True, default='0', max_length=30),
        ),
    ]
