# Generated by Django 3.0.7 on 2021-01-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_auto_20210111_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='impresion',
            name='datos_transaccion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='impresion',
            name='metodo_pago',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='impresion75',
            name='datos_transaccion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='impresion75',
            name='metodo_pago',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
