# Generated by Django 3.0.7 on 2021-01-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_auto_20210112_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='impresion',
            name='impuesto',
            field=models.CharField(blank=True, default='0', max_length=30),
        ),
        migrations.AddField(
            model_name='impresion',
            name='total',
            field=models.CharField(blank=True, default='0', max_length=30),
        ),
        migrations.AddField(
            model_name='impresion75',
            name='impuesto',
            field=models.CharField(blank=True, default='0', max_length=30),
        ),
        migrations.AddField(
            model_name='impresion75',
            name='total',
            field=models.CharField(blank=True, default='0', max_length=30),
        ),
    ]
