# Generated by Django 3.0.7 on 2020-11-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LotoChance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('thumb', models.ImageField(default='pic_folder/None/no-loto.jpg', upload_to='pic_folder/')),
                ('created_at', models.DateTimeField(editable=False)),
            ],
        ),
    ]
