# Generated by Django 3.0.7 on 2020-11-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotochance',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
