# Generated by Django 3.0.7 on 2020-11-24 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0001_initial'),
        ('chance', '0002_lotochance_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentaChance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(editable=False)),
                ('active', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TemporalChance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('numero', models.CharField(max_length=4)),
                ('monto', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(editable=False)),
                ('active', models.BooleanField(default=True)),
                ('loterias', models.ManyToManyField(to='chance.LotoChance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVentaChance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=4)),
                ('monto', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(editable=False)),
                ('active', models.BooleanField(default=True)),
                ('loterias', models.ManyToManyField(to='chance.LotoChance')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chance.VentaChance')),
            ],
        ),
    ]
