# Generated by Django 3.0.7 on 2020-11-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chance', '0003_detalleventachance_temporalchance_ventachance'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporalchance',
            name='total',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
